MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images"
COPY "C:\dev\AlphaHelp\helpfiles\Guides\Report\Adding System and Calculated Fields\images\Genie_button.gif" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images\Genie_button.gif"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images"
MOVE "C:\dev\AlphaHelp\helpfiles\Guides\Report\Creating Reports\images\quick_report_genie_columns.png" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images\quick_report_genie_columns.png"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images"
MOVE "C:\dev\AlphaHelp\helpfiles\Guides\Report\Creating Reports\images\quick_report_genie_filter_builder.png" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images\quick_report_genie_filter_builder.png"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images"
MOVE "C:\dev\AlphaHelp\helpfiles\Guides\Report\Creating Reports\images\quick_report_genie_groups.png" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images\quick_report_genie_groups.png"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images"
MOVE "C:\dev\AlphaHelp\helpfiles\Guides\Report\Creating Reports\images\quick_report_genie_preview.png" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images\quick_report_genie_preview.png"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images"
MOVE "C:\dev\AlphaHelp\helpfiles\Guides\Report\Creating Reports\images\quick_report_genie_settings.png" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images\quick_report_genie_settings.png"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images"
MOVE "C:\dev\AlphaHelp\helpfiles\Guides\Report\Creating Reports\images\quick_report_genie_styles.png" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images\quick_report_genie_styles.png"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images"
MOVE "C:\dev\AlphaHelp\helpfiles\Guides\Report\Creating Reports\images\size_columns_to_fit.png" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images\size_columns_to_fit.png"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images"
COPY "C:\dev\AlphaHelp\helpfiles\Guides\Report\Design Techniques\images\Acrobat_icon.gif" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images\Acrobat_icon.gif"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images"
COPY "C:\dev\AlphaHelp\helpfiles\Guides\Report\Design Techniques\images\Email_as_PDF_button.gif" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images\Email_as_PDF_button.gif"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images"
COPY "C:\dev\AlphaHelp\helpfiles\Guides\Report\Design Techniques\images\Print_button.gif" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images\Print_button.gif"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Design Techniques\images"
COPY "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images\Acrobat_icon.gif" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Design Techniques\images\Acrobat_icon.gif"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Design Techniques\images"
COPY "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images\Email_as_PDF_button.gif" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Design Techniques\images\Email_as_PDF_button.gif"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Adding System and Calculated Fields\images"
COPY "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images\Genie_button.gif" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Adding System and Calculated Fields\images\Genie_button.gif"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Design Techniques\images"
COPY "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images\Print_button.gif" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Design Techniques\images\Print_button.gif"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Report Structure\images"
COPY "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images\Report_Sections.gif" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Report Structure\images\Report_Sections.gif"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images"
MOVE "C:\dev\AlphaHelp\helpfiles\Guides\Report\Layout Table Reports\images\open_in_report_editor.png" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Quick Reports\images\open_in_report_editor.png"
MD "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images"
COPY "C:\dev\AlphaHelp\helpfiles\Guides\Report\Report Structure\images\Report_Sections.gif" "C:\dev\AlphaHelp\helpfiles\Guides\Report\Getting Started\images\Report_Sections.gif"
